<?php
/**
 * @package   Divante/rapid
 * @author    Kacper Chara <kchara@divante.pl>
 * @copyright 2017 Divante Sp. z o.o.
 * @license   See LICENSE_DIVANTE.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block Magento\Theme\Block\Html\Footer */
?>

<div class="copyright">
    <p><?php echo $block->getCopyright(); ?></p>
    <img class="rapid-image" src="https://divante.co/rapid.jpg" alt="Divante.co - eCommerce Software House"/>
</div>
