<?php
/**
 * @package   Divante/rapid
 * @author    Kacper Chara <kchara@divante.pl>
 * @copyright 2017 Divante Sp. z o.o.
 * @license   See LICENSE_DIVANTE.txt for license details.
 */
?>

<div id="footer-columns" class="footer-columns"
     data-mage-init='{
        "accordion":{
            "active": "",
            "collapsibleElement": ".single-column-heading",
            "content": ".single-column-content"
        }}'>
    <?php echo $block->getChildHtml('custom-footer'); ?>
</div>
