<?php
/**
 * @package Divante/rapid
 * @author Kacper Chara <kchara@divante.pl>
 * @copyright 2017 Divante Sp. z o.o.
 * @license See LICENSE_DIVANTE.txt for license details.
 */

/**
 * @var $block Magento\Framework\View\Element\Template
 */
?>

<div class="banner big-banner" style="background-image: url(<?php echo $block->getViewFileUrl('images/content/banners/banner9.jpg'); ?>)">
    <div class="banner-internal">
        <div class="banner-content">
            <h4 class="banner-tag">OUTLET</h4>
            <h3 class="banner-title">SEE EXCELLENT <br />CHANCES</h3>
            <a href="#" class="action on-dark-bg primary">View and shop now</a>
        </div>
    </div>
</div>
