<?php
/**
 * @package Divante/rapid
 * @author Kacper Chara <kchara@divante.pl>
 * @copyright 2017 Divante Sp. z o.o.
 * @license See LICENSE_DIVANTE.txt for license details.
 */

/**
 * @var $block Magento\Framework\View\Element\Template
 */
?>

<div class="hero-slider" data-mage-init='{"slider": {}}'>
    <div>
        <div class="hero-slide">
            <figure style="background-image: url(<?php echo $block->getViewFileUrl('images/content/slide1.jpg'); ?>)">
            </figure>
            <div class="container">
                <section>
                    <small>
                        <?php echo __('NEW COLLECTION'); ?>:
                    </small>
                    <h1>
                        <?php echo __('THIS IS PARADISE'); ?>
                    </h1>

                    <a href="#" class="action on-dark-bg">
                        [<?php echo __('VIEW AND SHOP NOW'); ?>]
                    </a>
                </section>
            </div>
        </div>
    </div>
    <div>
        <div class="hero-slide">
            <figure style="background-image: url(<?php echo $block->getViewFileUrl('images/content/slide1.jpg'); ?>)">
            </figure>
            <div class="container">
                <section>
                    <small>
                        <?php echo __('NEW COLLECTION'); ?>:
                    </small>
                    <h1>
                        <?php echo __('THIS IS PARADISE'); ?>
                    </h1>

                    <a href="#" class="action on-dark-bg">
                        [<?php echo __('VIEW AND SHOP NOW'); ?>]
                    </a>
                </section>
            </div>
        </div>
    </div>
    <div>
        <div class="hero-slide">
            <figure style="background-image: url(<?php echo $block->getViewFileUrl('images/content/slide1.jpg'); ?>)">
            </figure>
            <div class="container">
                <section>
                    <small>
                        <?php echo __('NEW COLLECTION'); ?>:
                    </small>
                    <h1>
                        <?php echo __('THIS IS PARADISE'); ?>
                    </h1>

                    <a href="#" class="action on-dark-bg">
                        [<?php echo __('VIEW AND SHOP NOW'); ?>]
                    </a>
                </section>
            </div>
        </div>
    </div>
</div>
