<?php
/**
 * @package Divante/rapid
 * @author Kacper Chara <kchara@divante.pl>
 * @copyright 2017 Divante Sp. z o.o.
 * @license See LICENSE_DIVANTE.txt for license details.
 */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<div class="block block-customer-login">
    <div class="block-centered">
        <div class="block-title">
            <strong id="block-customer-login-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Sign In') ?></strong>
        </div>
        <div class="block-content" aria-labelledby="block-customer-login-heading">
            <form class="form form-login"
                  action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
                  method="post"
                  id="login-form"
                  data-mage-init='{"validation":{}}'>
                <?php echo $block->getBlockHtml('formkey'); ?>
                <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                    <div class="field email required">
                        <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email Address:') ?></span></label>
                        <div class="control">
                            <input name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?>
                                   autocomplete="off"<?php endif; ?> id="email" type="email"
                                   class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email') ?>"
                                   data-validate="{required:true, 'validate-email':true}"
                                   placeholder="<?php echo __('Enter your Email Address'); ?>">
                        </div>
                    </div>
                    <div class="field password required">
                        <label for="pass" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
                        <div class="control">
                            <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?>
                                autocomplete="off"<?php endif; ?> class="input-text" id="pass"
                                title="<?php /* @escapeNotVerified */ echo __('Password') ?>"
                                data-validate="{required:true}"
                                placeholder="<?php echo __('Enter your Password'); ?>">
                        </div>
                    </div>
                    <?php echo $block->getChildHtml('form_additional_info'); ?>
                    <div class="actions-toolbar">
                        <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('Sign In') ?></span></button></div>
                        <div class="secondary"><a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span></a></div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>
