<?php
/**
 * @package Divante/rapid
 * @author Kacper Chara <kchara@divante.pl>
 * @copyright 2017 Divante Sp. z o.o.
 * @license See LICENSE_DIVANTE.txt for license details.
 */
?>
<div class="advantages-with-account">
    <p class="advantages-title"><strong><?php echo __('With an account you receive:'); ?></strong></p>
    <ul class="advantages-list">
        <li><i class="fa fa-shopping-cart" aria-hidden="true"></i> <?php echo __('Check out faster'); ?></li>
        <li><i class="fa fa-map-pin" aria-hidden="true"></i> <?php echo __('Keep more than one address'); ?></li>
        <li><i class="fa fa-search" aria-hidden="true"></i> <?php echo __('Track orders'); ?></li>
    </ul>
</div>
